server:
  port: 8886
  servlet:
    context-path: /cf

spring:
  profiles:
    # 切换环境 dev为开发环境，prod为生产环境
    active: dev
  jackson:
    serialization:
      write-dates-as-timestamps: true
  datasource:
    # 如果存在多个数据源，监控的时候可以通过名字来区分开来
    name: mysql
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # 驱动名字
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 扩展插件
    # 监控统计用的filter:stat 日志用的filter:log4j 防御sql注入的filter:wall
    filters: stat, wall
    # 最大连接池数量
    maxActive: 20
    # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
    initialSize: 5
    # 获取连接时最大等待时间，单位毫秒
    maxWait: 60000
    # 最小连接池数量
    minIdle: 5
    timeBetweenEvictionRunsMillis: 60000
    # 连接保持空闲而不被驱逐的最长时间
    minEvictableIdleTimeMillis: 300000
    # 用来检测连接是否有效的sql，要求是一个查询语句
    # 如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用
    validationQuery: select count(1) from 'table'
    # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
    testWhileIdle: true
    # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnBorrow: false
    # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
    # 是否缓存preparedStatement，即PSCache
    poolPreparedStatements: false
    # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true
    maxOpenPreparedStatements: -1

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


mybatis:
  # mapper.xml包地址
  mapper-locations: classpath:mapper/*.xml
  # pojo生成包地址
  type-aliases-package: team.fjut.cf.pojo
  configuration:
    map-underscore-to-camel-case: true

# PageHelper插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 自定义配置
cf:
  config:
    vj:
      problemListUrl: https://vjudge.net/problem/data
      remoteOJsUrl: https://vjudge.net/util/remoteOJs
      problemHtmlUrl: https://vjudge.net/problem/%s
      checkLoginStatusUrl: https://vjudge.net/user/checkLogInStatus
      doLoginUrl: https://vjudge.net/user/login
      submitUrl: https://vjudge.net/problem/submit
      captchaUrl: https://vjudge.net/util/captcha
      solutionUrl: https://vjudge.net/solution/data/%s